### ISSUE TITLE
Domain 4 - private cloud?

### ISSUE THREAD

**Issue by leenewcombe** [cloudsecurityalliance/CSA-Guidance#30]
The guidance is heavily focussed towards public cloud and the need to rely upon independent certifications and attestations - and quite rightly so.

However, I think the guidance would benefit from noting that the situation can be different when it comes to private cloud - as such a cloud is single tenant by nature then there is more scope to negotiate more traditional rights to audit.   Worth mentioning as this (right to audit) is one of the factors that has driven some organisations towards private cloud.

**Comment by pve** [comment]
I have heard say that other business unit tenants of a private cloud should be even less trusted than outside tenants. Even though business units may be part of the same organisation does not mean that they cannot heavily compete.

**Comment by leenewcombe** [comment]
Not my point :).   My point is that you can negotiate more specific terms and conditions when it comes to private cloud, including the right to audit.   I've seen a few clients going down the private cloud route solely because they can negotiate specific terms around availability, right to audit, data residency etc.

**Comment by rmogull** [comment]
Agree with Lee that in private cloud you can negotiate pretty much everything
