### ISSUE TITLE
Domain 6 - miscellaneous

### ISSUE THREAD

**Issue by leenewcombe** [cloudsecurityalliance/CSA-Guidance#32]
On the Management Plane front, it would be worthwhile considering how the management plane must enforce separation in a multi-tenant environment and reference to how this separation can be assured.

On the business continuity front, I think a reference to Chaos Engineering (e.g. the Netflix Simian Army) would be worthwhile as it shows how the cloud model can help organisations to build more resilient solutions overall.      

On the SaaS side of things, it's worthwhile noting that whilst you may be able to keep copies of your data for recovery purposes you are still stuffed from a continuity perspective without an application able to process that data!  Just having the data is insufficient to be comfortable you have continuity.  Kind of similar for PaaS depending upon how portable your code is.

**Comment by rmogull** [comment]
Great comments. All integrated.
