### ISSUE TITLE
Cloud Consumer

### ISSUE THREAD

**Issue by mmorozumi** [cloudsecurityalliance/CSA-Guidance#7]
The term 'Cloud Consumer' is ambiguous. It seems that it is the same as "Cloud Customer". If you use "Cloud Consumer", the definition of "Cloud Consumer" should be described.

**Comment by pve** [comment]
This is borrowed from NIST I think, and in domain 1.

Definition: a cloud consumer is the person or organization requesting and using the resources......

**Comment by rmogull** [comment]
Yep- it's a pretty common term. We use it synonymously with cloud customer per NIST and other documents,
