### ISSUE TITLE
Miss spells.

### ISSUE THREAD

**Issue by mmorozumi** [cloudsecurityalliance/CSA-Guidance#8]
In 1.1.2.1, 4th bullet, it has "This allows the to more closely...".
It should be "This allows them to more closely...".

In 1.1.3.1, 3rd paragraph, it has 'depoyment".
it should be 'deployment'.

in 1.1.3.1, 4th paragraph, it has 'abstration'.
It should be 'abstraction'.

In 1.2.1, it has "What does the consumer need need to do?".
It should be "What doe the consumer need to do?".

In 1.2.2, it has "FDIS 27017".
It should be '27071' because 27017 has already be published.

**Comment by rmogull** [comment]
Thanks... there are 2 more edit rounds still, I'm sure we will catch more! All fixed and doc updated.
